### ISSUE TITLE
Cant write to cron...zero error messages

### ISSUE THREAD

**Issue by davidmontgom** [doctormo/python-crontab#34]
Hi,

I am finding the documentation totally unusable

cron_str = '0 22 * * *'
cron    = CronTab(user='dude')
job  = cron.new(command='/usr/bin/echo')
job.setall(cron_str)
cron.write_to_user( user='dude' )

Yet there is cron in my crontab.  I am on a mac.

What am I missing?

nano crontab -e
EMPTY!!!!!!!

**Comment by davidmontgom** [comment]
I manually edited the cron...I guess is needed to be initialized with something.  I just added a comment and it worked

**Comment by doctormo** [comment]
That's actually very interesting, I didn't know this module would even work on Mac or if Mac even had crontabs. I have recieved no word from Mac users in all the years of development and the documentation does say it only supports Linux, Unix and Windows. (and unix means HP/UX, Oracle, etc)

Is the documentation unusable? Or did you find that it didn't function to initialise? do we have an initialisation problem because it SHOULD be initialising any crontab if possible.
